<?php
$isLogin=false;
$user=null;
$fuser=null;
$guser=null;
$country_model=new Application_Model_Country();
$destnations=$country_model->allcountry();
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$fpsession = new Zend_Session_Namespace('facebook');
$gogsession = new Zend_Session_Namespace('google');
if (!empty($sessionRead)) {
$isLogin=true;
$user=$sessionRead;

}elseif( (isset($fbsession->username) && !empty (isset($fbsession->username)))){
    $fuser=$fbsession->username;
}
?>
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="/"><i class="glyphicon glyphicon-flag"></i><strong> Le voyage</strong></a> </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse nav" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#services-section" class="page-scroll">Description</a></li>
                <li><a href="#team-section" class="page-scroll glyphicon glyphicon-map-marker">Map</a></li>
                <li><a href="#works-section" class="page-scroll">Locations</a></li>
                <?php
                if($isLogin){
                    ?>
                    <li><a href="#contact-section" class="page-scroll">Reservation</a></li>
                    <li> <a href="#rentCar" data-toggle="modal">Rent Car</a></li>
                    <li><a href="/user/editprofile" class="page-scroll">Profile</a></li>
                    <li><a href="/user/logout" class="page-scroll">LogOut</a></li>
                    <?php
                }
                ?>
                <li><a href="#city-expe" class="page-scroll">Experience</a></li>
                <?php
                if(!$isLogin&&!$fuser){
                    ?>
                    <li><a href="/user/login" class="page-scroll">LogIn</a></li>
                    <?php
                }
                ?>
                <li class="dropdown">
                    <a href="#" class=" glyphicon glyphicon-globe" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Destinations <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php
                        foreach ($destnations as $country):
                            ?>
                            <li ><a href="/index/getcities/conid/<?=$country['id']?>" class=""><?=$country['name']?></a></li>
                            <li role="separator" class="divider"></li>
                            <?php
                        endforeach;
                        ?>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<!-- Header -->
<header class="text-center" id ="home" style="	background: url(/images/<?=$this->city->image_path?>) no-repeat bottom center;">
    <div class="intro-text">
        <h1 class="wow fadeInDown" data-wow-delay="3000ms"><strong><span class="color"><?=$this->city->name?></span></strong></h1>
        <a href="#services-section" class="btn btn-default btn-lg page-scroll wow fadeInUp" data-wow-delay="3000ms">City Description</a> </div>
</header>

<!-- Description  -->
<div id="services-section" class="text-center">
    <div class="container">
        <div class="section-title wow fadeInDown">
            <h2><?=$this->city->name?><strong> Description</strong> </h2>
            <hr>
            <div class="clearfix">
                <?=$this->city->description?>
            </div>
        </div>
    </div>
</div>
<!--------------- Description  -->

<!-- Team Section -->
<div id="team-section" class="text-center">
    <div class="container">
        <div class="section-title wow fadeInDown">
            <h2> <?=$this->city->name?><strong> Map</strong></h2>
            <hr>
            <div class="clearfix">
            </div>
            <div id="map" class="table-responsive" style=" height:450px ;border:3px solid white ">
            </div>
        </div>

    </div>
</div>
<?php
if($isLogin) {
    include "modal_alarms.php";
    ?>
    <!-- Hotel Section -->
    <div id="contact-section" class="text-center">
        <div class="container">
            <div class="section-title wow fadeInDown">
                <h2><strong>Hotel</strong> Reservation</h2>
                <hr>
                <h3>Book Now..</h3>
            </div>
            <form>
            <div class="col-md-8 col-md-offset-2 wow fadeInUp" data-wow-delay="200ms">
                <div class="col-md-4"><i class="fa fa-map-marker fa-2x"></i>
                    <?= $this->hotel_form->getElement("from");?>
                </div>
                <div class="col-md-4"><i class="fa fa-envelope-o fa-2x"></i>
                    <?= $this->hotel_form->getElement("to");?>
                </div>
                <div class="col-md-4"><i class="fa fa-phone fa-2x"></i>
                    <?= $this->hotel_form->getElement("members");?>
                </div>
                <div class="clearfix"></div>
            </div>
            <br><br><br>
            <div class="col-md-8 col-md-offset-2 wow fadeInUp" data-wow-delay="200ms">
                <div class="col-md-8"><i class="fa fa-map-marker fa-2x"></i>
                    <select  id="hotels" class="form-control">
                        <option>---Select Hotel---</option>
                        <?php
                        foreach ($this->hotels as $hotel):
                            ?>
                            <option><?=$hotel->name ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div class="row">
                    <div class="col-md-3"><i class="fa fa-phone fa-2x"></i>
                        <?= $this->hotel_form->getElement("reset");?>
                    </div>
                    <div class="col-md-3"><i class="fa fa-phone fa-2x"></i>

                        <button type="submit" class="btn btn-default hotel_submit">Check In</button>
                </div>
                <input type="hidden" value="<?=$user->id ?>" class="user_id">

                <div class="clearfix"></div>
                <br><br>
            </div>

            </form>
            <div class="col-md-8 col-md-offset-2 wow fadeInUp" data-wow-delay="400ms">
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-github"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
    <?php
}
?>

<!-- Portfolio Section ----------- locations!--->

<div id="works-section" class="text-center">
    <div class="container"> <!-- Container -->

        <div class="section-title wow fadeInDown">
            <h2><?=$this->city->name?><strong>Locations</strong></h2>
            <hr>
            <div class="clearfix"></div>
        </div>
        <div class="row">
            <div class="portfolio-items">
                <?php
                $tim=400;
                foreach ($this->locations as $location):
                ?>
                <div class="col-sm-6 col-md-3 col-lg-3 web">
                    <div class="portfolio-item wow fadeInUp" data-wow-delay="<?=$tim?>ms">
                        <div class="hover-bg"> <a href="#locationModal<?= $location->id?>" class="portfolio-link" data-toggle="modal">
                                <div class="hover-text">
                                    <h4><?= $location->name?></h4>
                                    <div class="clearfix"></div>
                                    <i class="fa fa-plus"></i> </div>
                                <img src="/images/<?= $location->image_path?>" class="img-responsive" alt="Location Image"> </a> </div>
                    </div>
                </div>
                    <?php
                $tim+=200;
                endforeach;
                ?>

            </div>

        </div>


    </div>

</div>

<!-------------------------locations  modals !------------------------>
<?php
foreach ($this->locations as $location):
?>

    <!-- Portfolio Modal 3 -->
    <div class="portfolio-modal modal fade" id="locationModal<?= $location->id?>" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl"> </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2><?= $location->name?></h2>
                            <p class="item-intro">Lorem ipsum dolor sit amet consectetur.</p>
                            <img class="img-responsive img-centered" src="/images/<?= $location->image_path?>" alt="">
                            <p><?= $location->description?></p>
                            <ul class="list-inline">
                                <li><strong>City</strong>: <?=$this->city->name?></li>
                            </ul>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    endforeach;
    ?>
    <div class="portfolio-modal modal fade" id="rentCar" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl"> </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <h2>Rent Car</h2>
                            <form role="form">
                                <div class="form-group col-md-6">
                                    <label for="pickTime"><span class="glyphicon glyphicon-time"></span> pick Time</label>
                                    <input type="datetime-local" class="form-control " id="pickTime" placeholder="Time" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="leaveTime"><span class="glyphicon glyphicon-time"></span> Leaving Time</label>
                                    <input type="datetime-local" class="form-control " id="leaveTime" placeholder="Time" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fa fa-map-marker fa-2x"></i>
                                    <label for="fromLocation"><span class="glyphicon glyphicon-home"></span> From</label>
                                    <select  id="fromLocation" class="form-control">
                                        <option>---Select Location---</option>
                                        <?php
                                        foreach ($this->locations as $location):
                                            ?>
                                            <option value="<?=$location->id ?>"><?=$location->name ?></option>
                                            <?php
                                        endforeach;
                                        ?>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fa fa-map-marker fa-2x"></i>
                                    <label for="toLocation"><span class="glyphicon glyphicon-home"></span> To</label>
                                    <select  id="toLocation" class="form-control">
                                        <option>---Select Location---</option>
                                        <?php
                                        foreach ($this->locations as $location):
                                            ?>
                                            <option value="<?=$location->id ?>"><?=$location->name ?></option>
                                            <?php
                                        endforeach;
                                        ?>
                                    </select>
                                </div>
                                <button type="submit" id="rentCarSubmit" class="btn btn-primary">Rent Now</button>
                            </form>
                            <br>
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>tio
    </div>


<!------------------------end-locations  modals !------------------------>
<iframe  id="city-expe" src="/index/exper/id/<?=$this->city->id?>/page/1" style="width: 100%;height: 600px ;border: none"></iframe>

<script>
    function initMap() {
        var mapDiv = document.getElementById('map');
        var myLatLng = {lat:  <?= $this->city->lat?>, lng: <?= $this->city->longd?>};
        var map = new google.maps.Map(mapDiv, {
            center: myLatLng,
            zoom: 8
        });
        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: '<?= $this->city->name?>'
        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>
<!--<script type="text/javascript" src="/bootstrap/js/SmoothScroll.js"></script>-->

<script src="/bootstrap/js/city_script.js"></script>
<script src="/bootstrap/js/bootstrap-datepicker.js"></script>
<script> $('.date_field').datepicker('hide');</script>
