<!--<a href="/index/exper/id/1/page/1#disqus_thread">Link</a> -->
<?php
foreach ($this->paginator as $exp):
	?>
	<div class="text-center">
		<?=
		$this->paginationControl($this->paginator,
			'Sliding',
			"index/paginatorControl.phtml");
		?>
	</div>

	<div  class="container-fluid bg-warning text-primary " style=" width:100% ;height:700px">
		<img class="exp-img"  src="/images/<?=$exp['image_path']?>" style=" width:60% ;height:300px">
		<div  class="exp-content container-fluid bg-warning text-primary" style=" width:90% ;height:300px ;border: 1px solid">
			<?=$exp['content']?>
		</div>
		<div class="text-center">
			<?=
			$this->paginationControl($this->paginator,
				'Sliding',
				"index/paginatorControl.phtml");
			?>
		</div>
	</div>
	<?php
endforeach;
?>
<script>
	$("#levoyage-nav").remove();
</script>

<div class="container">
	<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//levoyage-iti.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>

<script id="dsq-count-scr" src="//levoyage-iti.disqus.com/count.js" async></script>
