<!--<a href="/index/exper/id/1/page/1#disqus_thread">Link</a> -->
<?php
$isLogin=false;
$user=null;
$fuser=null;
$guser=null;
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$fpsession = new Zend_Session_Namespace('facebook');
$gogsession = new Zend_Session_Namespace('google');

if (!empty($sessionRead)) {
	$isLogin=true;
	$user=$sessionRead;
	include "disqus.phtml";
	?>
<script type="text/javascript" xmlns="http://www.w3.org/1999/html">
	var disqus_config = function() {
		this.page.remote_auth_s3 = "<?php echo "$message $hmac $timestamp"; ?>";
		this.page.api_key = "<?php echo DISQUS_PUBLIC_KEY; ?>";
	}
</script
<?php

}elseif( (isset($fbsession->username) && !empty (isset($fbsession->username)))){
	$fuser=$fbsession->username;
}elseif((isset($gogsession) && !empty (isset($gogsession)))){
    $guser=$gogsession;
    include "disqus.phtml";
    ?>
<script type="text/javascript">
	var disqus_config = function() {
		this.page.remote_auth_s3 = "<?php echo "$message $hmac $timestamp"; ?>";
		this.page.api_key = "<?php echo DISQUS_PUBLIC_KEY; ?>";
	}
</script
<?php
}
?>
<link rel="stylesheet" type="text/css"  href="/bootstrap/css/city-style.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/city-animate.min.css">
<link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="/bootstrap/js/modernizr.custom.js"></script>
<style>
	#exp-header{
		background: url(/bootstrap/images/header-bg.jpg) ;
		background-size: cover;
	}
	#exp-img-div{
		flow-into: ;
		display:inline-block;
		float: left;
		margin-bottom: 5px;width: 60%;
	}
	#exp-img{
		width: 100%;
		height: 400px;
		border: 1px solid yellow;
	}
	#exp-content{
		color: whitesmoke;
		padding: 10px;
		float: right;
		width: 38% ;
		word-wrap: break-word;
		border-bottom: 2px solid yellow;
		border-top: 2px solid yellow
	}
</style>

<div id="preloader">
	<div id="status"> <img src="/bootstrap/images/preloader.gif" height="64" width="64" alt=""> </div>
</div>
<!-- Header -->
<header id="exp-header" class="text-center " name="home">
	<div class="intro-text">
		<h1 class="wow fadeInDown">Visitors <strong><span class="color">Experience</span></strong></h1>
			<?php foreach ($this->paginator as $exp):
			?>

		<h2><span class="color col-md-6">	<?php echo $exp['title']."</span></h2>";
		?>
</div>
</header>

<span id="exp-img-div">
	<img id="exp-img" src="/images/<?= $exp['image_path']?>">
	</span>

<span id="exp-content" class="page-scroll wow fadeInUp" data-wow-delay="300ms">
		<p>

			<?php echo $exp['content']."</p>
			</span>
			<div style='clear:both'>";
			if($isLogin){
		?>
			<a href="/user/addexper/id/<?= $this->city_id?>" class="btn btn-default btn-lg page-scroll wow fadeInUp" data-wow-delay="200ms">Add Experience</a>
	<?php
			if($exp['user_id']==$user->id){
				?>
				<a href="/user/bactocty/pid/<?= $exp['id']?>/cid/<?=$this->city_id?>" class="btn btn-default btn-lg page-scroll wow fadeInUp" data-wow-delay="400ms">Edit</a>
				<a href="/user/deleteexper/pid/<?= $exp['id']?>/cid/<?=$this->city_id?>" class="btn btn-default btn-lg page-scroll wow fadeInUp" data-wow-delay="400ms">Delete</a>
				<?php
			}
	}
			?>
			</div>
				<div class="text-center page-scroll wow fadeInUp" data-wow-delay="500ms">
		<p>
		<?=

			$this->paginationControl($this->paginator,
				'Sliding',
				"index/paginatorControl.phtml");
			?>
	</p></p>
			<br>
		</div>
			<?php
		endforeach;
		?>

<div id="disqus_thread"></div>
<script>
	$(function(){
		$("#top").remove();
		$("#footer").remove();
	});

</script>
<script type="text/javascript" src="/bootstrap/js/SmoothScroll.js"></script>
<script type="text/javascript" src="/bootstrap/js/wow.min.js"></script>
<script type="text/javascript" src="/bootstrap/js/jquery.isotope.js"></script>
<script type="text/javascript" src="/bootstrap/js/jqBootstrapValidation.js"></script>
<script type="text/javascript" src="/bootstrap/js/owl.carousel.js"></script>
<script type="text/javascript" src="/bootstrap/js/main.js"></script>


<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//levoyage-iti.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
<style>
	body{background: rgb(3,39,49)}
</style>
<script id="dsq-count-scr" src="//levoyage-iti.disqus.com/count.js" async></script>
