 <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/bootstrap/assets/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/bootstrap/assets/css/form-elements.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/style.css">
                <style >
                    .container-fluid {
    background-image: url("/bootstrap/assets/img/backgrounds/5.jpg") ;
    background-size: 100% ;
                        padding: 30px;
    }

    </style>

                <div class="container-fluid">
                     <div class="row">    	
                        <div class="col-md-12 " >
                        	<!-- <div class="form-box"> -->
	                        	<br><strong class="coun"><?= $this->countrydata->name ?></strong><br>
	                        	<img class="top"src="/images/<?php echo $this->countrydata->image_path ?>" class="img-thumbnail" alt="Cinque Terre" ><br>
	                        <!-- </div -->
	                    <hr>
    <nav class="navbar  ">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav " style="float:left">
                         <?php foreach ($this->cities as $key => $value) : ?>
	                          <?php echo "<li><a href='/index/city/id/". $value['id']."' >
	                            	<img id='city' src='/images/". $value['image']."' class=\"img-thumbnail\" alt=\"Cinque Terre\" width=\"236\" height=\"236\"/></a></li>
	                            	<li><a><strong>".$value['name']."</strong></a></li>";?>
	                       <?php endforeach; ?>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        <!-- /.container -->
    </nav>
	                       </div>
	                 </div>
                    <div id="map" class="table-responsive" style=" height:450px ;border:3px solid white ">
                    </div>
	            </div>
 <script>
     function initMap() {
         var mapDiv = document.getElementById('map');
         var myLatLng = {lat:  <?= $this->countrydata->lat?>, lng: <?= $this->countrydata->longd?>};
         var map = new google.maps.Map(mapDiv, {
             center: myLatLng,
             zoom: 8
         });
         var marker = new google.maps.Marker({
             position: myLatLng,
             map: map,
             title: '<?= $this->countrydata->name?>'
         });
     }
 </script>
 <script src="/bootstrap/assets/js/jquery.backstretch.min.js"></script>
        <script src="/bootstrap/assets/js/scripts.js"></script>








