<br /><br />
<div id="view-content">
</div>
<?php
//foreach($this->cities as $key=>$value){
//	echo $key.": " .$value->name;
//}

echo "<center><strong class=\"footer-logo\">".$this->countrydata->name."</strong></center>";


?>
<body>
<div class="row">
	<div class="col-sm-12"><img src="/images/<?php echo $this->countrydata->image_path ?>" class="img-thumbnail" alt="Cinque Terre" width="1000" height="236"></div>

</div>

<?php

foreach($this->cities as $key=>$value)
{
	echo "<table class=\"info\"><thead><tr class=\"success\">";
	echo "<td><a href='/index/city/id/". $value['id']."' ><img src='/images/". $value['image']."' class=\"img-thumbnail\" alt=\"Cinque Terre\" width=\"236\" height=\"236\"/></td></a>";
	//echo "/images/". $value['image'];
	echo "<td><strong class=\"footer-logo\">".$value['name']."</strong><br>" ;
	echo "<center>Rate: " .$value['rate']."</center></td></tr></tbody></table>";
	//echo ":image path: " .$value['image'];


}
?>

</body>

