<?php
$isLogin=false;
$user=null;
$fuser=null;
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$fpsession = new Zend_Session_Namespace('facebook');

if (!empty($sessionRead)) {
$name = $sessionRead->username;
$isLogin=true;
$user=$sessionRead;
}elseif( (isset($fbsession->username) && !empty (isset($fbsession->username)))){
$fuser=$fbsession->username;
}
?>

  <link href="/bootstrap/css/full-slider.css" rel="stylesheet">
    <!-- Navigation -->
    
    <!-- Custom CSS -->
  

    <!-- Full Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
        </ol>
        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->

 <div class="fill">

<div class="img">
  <a  href="/index/getcities/conid/<?=$this->countries[0]['id']?>">
    <img src="/images/<?=$this->countries[0]['image_path']?>" alt="Trolltunga Norway" width="1300" height="700">
  </a>        </div>

</div>

                <div class="carousel-caption">
                    <h1><?php echo $this->countries[0]['name']?></h1>
                </div>

            </div>


           
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="img">
                     <a  href="/index/getcities/conid/<?=$this->countries[1]['id']?>">
                         <img src="/images/<?=$this->countries[1]['image_path']?>" alt="Trolltunga Norway" style="width:100%" height="600">
                     </a>       
                </div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[1]['name']?></h1>
                </div>
            </div>

            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="img">
                    <a  href="/index/getcities/conid/<?=$this->countries[2]['id']?>">
                        <img src="/images/<?=$this->countries[2]['image_path']?>" alt="Trolltunga Norway" width="1300" height="700">
                    </a>        
                </div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[2]['name']?></h1>
                </div>
            </div>
        
        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="img">
                     <a  href="/index/getcities/conid/<?=$this->countries[3]['id']?>">
                        <img src="/images/<?=$this->countries[3]['image_path']?>" alt="Trolltunga Norway" width="1300" height="700">
                    </a>        
                </div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[3]['name']?></h1>
                </div>
        </div>
        

        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="img">
                     <a  href="/index/getcities/conid/<?=$this->countries[4]['id']?>">
                        <img src="/images/<?=$this->countries[4]['image_path']?>" alt="Trolltunga Norway" width="1300" height="700">
                     </a>        
                </div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[4]['name']?></h1>
                </div>
         </div>
        

        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
               <div class="img">
                    <a  href="/index/getcities/conid/<?=$this->countries[5]['id']?>">
                        <img src="/images/<?=$this->countries[5]['image_path']?>" alt="Trolltunga Norway" width="1300" height="700">
                     </a>        
                </div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[5]['name']?></h1>
                </div>
        </div>
</div>
        
        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>


    </header>

    <!-- Page Content 22-->
    <div class="container">
<br><br><br><br>
        <div class="row">
  <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[0]['id']?>" class="thumbnail">
      <img src="/images/<?=$this->cities[0]['image_path']?>" style="width:300px; height:200px;">
    </a>
  </div>
  <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[1]['id']?>" class="thumbnail" class="thumbnail">
      <img src="/images/<?=$this->cities[1]['image_path']?>"style="width:300px; height:200px;">
    </a>
  </div>
   <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[2]['id']?>" class="thumbnail" class="thumbnail">
      <img src="/images/<?=$this->cities[2]['image_path']?>"style="width:300px; height:200px;">
    </a>
  </div>
 
</div>
    <div class="row">
  <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[3]['id']?>" class="thumbnail" class="thumbnail">
      <img src="/images/<?=$this->cities[3]['image_path']?>"style="width:300px; height:200px;" >
    </a>
  </div>
  <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[4]['id']?>" class="thumbnail" class="thumbnail">
      <img src="/images/<?=$this->cities[4]['image_path']?>"style="width:300px; height:200px;">
    </a>
  </div>
   <div class="col-xs-6 col-md-4">
    <a href="/index/city/id/<?=$this->cities[5]['id']?>" class="thumbnail" class="thumbnail">
      <img src="/images/<?=$this->cities[5]['image_path']?>"style="width:300px; height:200px;">
    </a>
  </div>
 
</div>
        <hr>

        <!-- Footer -->
      
</div>

            
        

        

        <!-- Footer -->
  
    <!-- /.container -->

    <!-- jQuery -->


    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 2500 //changes the speed
    })
    </script>

