<?php
$isLogin=false;
$user=null;
$fuser=null;
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$fpsession = new Zend_Session_Namespace('facebook');

if (!empty($sessionRead)) {
$name = $sessionRead->username;
$isLogin=true;
$user=$sessionRead;
}elseif( (isset($fbsession->username) && !empty (isset($fbsession->username)))){
$fuser=$fbsession->username;
}
?>
    <!-- Custom CSS -->
    <link href="/bootstrap/css/full-slider.css" rel="stylesheet">
    <!-- Full Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
        </ol>
        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->


                <div class="fill" style="   background-image: url(/images/<?=$this->countries[0]['image_path']?>) ;"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[0]['name']?></h1>
                </div>
            </div>
           
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="   background-image: url(/images/<?=$this->countries[1]['image_path']?>) ;"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[1]['name']?></h1>
                </div>
            </div>

            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="   background-image: url(/images/<?=$this->countries[2]['image_path']?>) ;"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[2]['name']?></h1>
                </div>
            </div>
        


        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="   background-image: url(/images/<?=$this->countries[3]['image_path']?>) ;"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[3]['name']?></h1>
                </div>
            </div>
        

        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="   background-image: url(/images/<?=$this->countries[4]['image_path']?>) ;"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[4]['name']?></h1>
                </div>
            </div>
        

        <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div  class="fill " style="background-image: url(/images/<?=$this->countries[5]['image_path']?>);"></div>
                <div class="carousel-caption">
                    <h1><?php echo $this->countries[5]['name']?></h1>
                </div>
            </div>
        </div>


        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>






    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
            </div>
        </div>

        

        <!-- Footer -->


    </div>
    <!-- /.container -->

    <!-- jQuery -->


    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 2500 //changes the speed
    })
    </script>
