<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
        of <?php echo $this->totalItemCount; ?>

        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>"class="btn btn-default">
                First
            </a> |
        <?php else: ?>
            <span class="disabled btn btn-default">First</span> |
        <?php endif; ?>

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>"class="btn btn-default">
                &lt; Previous
            </a> |
        <?php else: ?>
            <span class="disabled btn btn-default">&lt; Previous</span> |
        <?php endif; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>"class="btn btn-default">
                Next &gt;
            </a> |
        <?php else: ?>
            <span class="disabled btn btn-default ">Next &gt;</span> |
        <?php endif; ?>

        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->last)); ?>" class="btn btn-default">
                Last
            </a>
        <?php else: ?>
            <span class="disabled btn btn-default ">Last</span>
        <?php endif; ?>

    </div>
<?php endif; ?>