<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.
min.css" integrity="sha384-
1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-
theme.min.css" integrity="sha384-
fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
crossorigin="anonymous"></script>
</head>

<nav class="navbar navbar-default navbar-fixed-top">
<p class="navbar-text" style="float:right;">

	
<?php
$fbsession = new Zend_Session_Namespace('facebook');
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (!empty($sessionRead)) {
$name = $sessionRead->username;
echo "Welcome " . $name;
echo '<a class="btn btn-default navbar-btn" href="'. $this->baseUrl() .'/user/logout"> Logout </a>';
 echo' <a class="btn btn-default navbar-btn" href="'. $this->baseUrl() .'/user/editprofile"> update profile </a>';
 echo' <a class="btn btn-default navbar-btn" href="'. $this->baseUrl() .'/index"> Home </a>';
}

elseif (isset($fbsession->username) && !empty (isset($fbsession->username))) {
$name = $fbsession->username;
echo "Welcome " . $name;
?>
 <a class="btn btn-default navbar-btn" href="<?php echo $this->baseUrl() ?>/user/fblogout"> Logout </a>
echo' <a class="btn btn-default navbar-btn" href="<?php echo $this->baseUrl() ?>/index"> Home </a>';
<?php
}
?>
</p>
</nav><br><br><br><br>
<?php echo $this->layout()->content; ?>
