<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/bootstrap/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/bootstrap/assets/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/bootstrap/assets/css/form-elements.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="/bootstrap/assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
        <style >
        body {
    background-image: url("/bootstrap/assets/img/backgrounds/1.jpg") ;
    background-size: 100% ;
    background-repeat: no-repeat;}
    b{
    	color:#bd4b00;
    }
    </style>


    </head>

    <body >

        <!-- Top content -->
        <div class="top-content">
        	
            <div class="inner-bg">
                <div class="container">
                <div class="row">
                        	
                        <div class="col-md-5 col-md-offset-3" >
                        	
                        	<div class="form-box">
                        		<div class="form-top">
	                        		<div class="form-top-left">
	                        			<h3>Sign up now</h3>
	                            		<p>Fill in the form below to get instant access:</p>
	                        		</div>
	                        		<div class="form-top-right">
	                        			<i class="fa fa-pencil"></i>
	                        		</div>
	                            </div>

	                            <div class="form-bottom">             

				                        	<?php echo $this->register_form;?>

 				                    </div>
	                        	</div>
	                        	
	                        </div>
	                    </div>
	                    
	                </div>
	            </div>
	            
	        </div>

        <!-- Javascript -->
<!--         <script src="/bootstrap/assets/js/jquery-1.11.1.min.js"></script>
 -->       <script src="/bootstrap/assets/js/jquery.backstretch.min.js"></script>
        <script src="/bootstrap/assets/js/scripts.js"></script>
        
        <!--[if lt IE 10]>
            <script src="/bootstrap/assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>
