<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/bootstrap/assets/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/bootstrap/assets/css/form-elements.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
	<style type="text/css">
        body {
    background-image: url("/bootstrap/assets/img/backgrounds/3.jpg") ;
    background-size: 1250px ;
    background-repeat: no-repeat;}
	</style>
</head>
<body>

<!-- Top content -->
        <div class="top-content ">
        	
            <div class="inner-bg">
                <div class="container">
 
                    <div class="row">
                        <div class="col-md-5 ">
                        	
                        	<div class="form-box">
	                        	<div class="form-top">
	                        		<div class="form-top-left">
	                        			<h3>Edit Your Experience</h3>
	                        		</div>
	                            </div>
	                            <div class="form-bottom">

	                            	<?php	echo $this->exper_form;?>
			                    </div>
		                    </div>		                        	

	                        	</div>
	                        </div>
	                        
                        </div>
					                  
				    </div>
	           </div>




        <!-- Javascript -->

        <script src="/bootstrap/assets/js/jquery.backstretch.min.js"></script>
        <script src="/bootstrap/assets/js/scripts.js"></script>
        <script type="text/javascript">
        	$("#selectedFile").on("click",fuction(){
        		alert("kljsdhskjdg");
        	})
        </script>
        
        <!--[if lt IE 10]>
            <script src="/bootstrap/assets/js/placeholder.js"></script>
        <![endif]-->







</body>
</html>

