        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/bootstrap/assets/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/bootstrap/assets/css/form-elements.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <style >
        body {
    background-image: url("/bootstrap/assets/img/backgrounds/1.jpg") ;
    background-size: 100% ;
    background-repeat: no-repeat;}
    b{
    	color:#bd4b00;
    }
    </style>
		<div style="height:75px"></div>
		<div class="top-content ">
		   <div class="inner-bg">
		       <div class="container">
		           <div class="form-bottom">
                        <ul class="nav nav-tabs col-sm-12">
                           <li class="active"><a href="#personal_Data" data-toggle="tab">       Edit_Profile</a></li>
                           <li><a href="#car_rental" data-toggle="tab">car_rental</a></li>
                           <li><a href="#hotel_reservation" data-toggle="tab">hotel_reservation</a></li>
                         </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="personal_Data">
                <div class="form-group ">
                 <?php echo $this->user_form ;?>
                </div>
                	
            </div><!--first tab-->

            <div class="tab-pane" id="car_rental">  <!--second tab-->
            		i
	             <div class="table-responsive">
			             <table class="table table-striped table-bordered table-hover">
			                 <tr class="danger">
									<th>from</th>
									<th>to</th>
									<th>pick_time</th>
									<th>leaving_time</th>
			                 </tr>
			                <tbody>
							      	<?php foreach ($this->cars as $key => $value) :

                                        ?>

							     	 	<tr class="warning text-danger">
										    <td> <?= $value->from_city ?>     </td>
											<td> <?= $value->to_city ?>       </td>
											<td> <?= $value->pick_time ?>     </td>
											<td> <?= $value->leaving_time ?>  </td>
										</tr>
                                        <?php endforeach; ?>
			                </tbody>
			            </table>
	             </div>
            </div> <!--end second tab-->

		            <div class="tab-pane" id="hotel_reservation"><!--tab 3-->
		            i
		                <div class="table-responsive">
		                <table class="table table-striped table-bordered table-hover">
		                   <tr class="danger">
			                     <th>Hote Name</th>
			                     <th>Time To</th>
			                     <th>Time From</th>
			                     <th>number of memebers</th>
                                 <th>number of Rooms</th>
		                   </tr>
		                   
		                   <tbody>
                         <?php foreach ($this->hotels as $key => $value) : ?>
				                <tr class="warning text-danger">
				                    <td><?=$value->hotel_name?></td>
				                    <td><?=$value->time_to?></td>
				                    <td><?=$value->time_from?></td>
				                    <td><?=$value->num_member?></td>
                                    <td><?=$value->num_rooms?></td>
				                </tr>
                                <?php endforeach; ?>
		                   </tbody> 
		                </table>

		                </div>
		            </div>
	         </div>
       </div>
       		</div>
       		</div></div>
      
        <script src="/bootstrap/assets/js/jquery.backstretch.min.js"></script>
        <script src="/bootstrap/assets/js/scripts.js"></script>
