<br /><br />
<div id="view-content">
</div>
<?php
//foreach($this->cities as $key=>$value){
//	echo $key.": " .$value->name;
//}

echo "<center><strong class=\"footer-logo\">".$this->countrydata->name."</strong></center>";


?>
<div class="row">
	<div class="col-sm-12"><img src="<?php echo $this->countrydata->image_path ?>" class="img-thumbnail" alt="Cinque Terre" width="1000" height="236"></div>

</div>

<?php

foreach($this->cities as $key=>$value)
{
	echo "<table class=\"info\"><thead><tr class=\"success\">";
	echo "<td><img src=". $value['image']." class=\"img-thumbnail\" alt=\"Cinque Terre\" width=\"236\" height=\"236\"/></td>";

	echo "<td><strong class=\"footer-logo\">".$value['name']."</strong><br>" ;
	echo "<center>Rate: " .$value['rate']."</center></td></tr></tbody></table>";
	//echo ":image path: " .$value['image'];


}
?>
<div id="map" class="table-responsive" style=" height:450px ;border:3px solid white ">
</div>
<script>
	function initMap() {
		var mapDiv = document.getElementById('map');
		var myLatLng = {lat:  <?= $this->countrydata->lat?>, lng: <?= $this->countrydata->longd?>};
		var map = new google.maps.Map(mapDiv, {
			center: myLatLng,
			zoom: 8
		});
		var marker = new google.maps.Marker({
			position: myLatLng,
			map: map,
			title: '<?= $this->countrydata->name?>'
		});
	}
</script>


