 <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/bootstrap/assets/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/form-elements.css">
        <link rel="stylesheet" href="/bootstrap/assets/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="/bootstrap/assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">



        <style >
        body {
    background-image: url("/bootstrap/assets/img/backgrounds/1.jpg") ;
    background-size: cover ;
        }
    b{
    	color:#bd4b00;
    }
    </style>
        <!-- Top content -->
        <div class="top-content ">
        	
            <div class="inner-bg">
                <div class="container">
 
                    <div class="row">
                        <div class="col-md-5 col-md-offset-3 ">
                        	
                        	<div class="form-box">
	                        	<div class="form-top">
	                        		<div class="form-top-left">
	                        			<h3>Login to our site</h3>
	                            		<p>Enter email and password to log on:</p>
	                        		</div>
	                        		<div class="form-top-right">
	                        			<i class="fa fa-lock"></i>
	                        		</div>
	                            </div>
	                            <div class="form-bottom">

				                        <?php echo $this->login_form;?>

			                    </div>
		                    </div>
		                
		                	<div class="social-login">
	                        	<div class="social-login-buttons">
		                        	<?php echo'<a class="btn btn-link-2 " href="' . htmlspecialchars( $this->facebook_url) . '" >'?>
		                        		<i class="fa fa-facebook"></i> Facebook
		                        	</a>
		                        	<?php echo'<a class="btn btn-link-2" href="' . htmlspecialchars( $this->twitterUrl) . '">'?>
		                        		<i class="fa fa-twitter"></i> Twitter
		                        	</a>
		                        	<?php echo'<a class="btn btn-link-2" href="' . $this->google_url . '">'?>
		                        		<i class="fa fa-google-plus"></i> Google Plus
		                        	</a>		                        	

	                        	</div>
	                        </div>
	                        
                        </div>
					                   
				                    </div>
	                        	</div>
	                        	
	                        </div>
	                    </div>
	                    
	                </div>
	            </div>
	            
	        </div>



        <!-- Javascript -->
        <script src="/bootstrap/assets/js/jquery.backstretch.min.js"></script>
        <script src="/bootstrap/assets/js/scripts.js"></script>
        <script type="text/javascript">
        var ff=document.getElementById('file');
        ff.addEventListner("click",function(){
            alert("fdfdfdfdf");
        });
                          
        </script>
        <!--[if lt IE 10]>
            <script src="/bootstrap/assets/js/placeholder.js"></script>
        <![endif]-->




