<?php
$isLogin=false;
$user=null;
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (!empty($sessionRead)) {
	$name = $sessionRead->username;
	$is_admin=$sessionRead->is_admin;
	$isLogin=true;
	$user=$sessionRead;

}
if ($isLogin && $is_admin) {
$name = $user->username;


?>
<div class="container" >
	<nav id="top" class="navbar navbar-default navbar-fixed-top">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			<a class="navbar-brand" href="/"><i class="glyphicon glyphicon-flag"></i><strong> Le voyage</strong></a>
			<?php
			if($isLogin){
			?>
			<a class="navbar-brand" href="/user/editprofile"><i
					class="glyphicon glyphicon-user"></i><strong> <?= $name ?></strong></a>
		</div>
		<?php
		}
		?>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse nav" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/admin/index" class="page-scroll glyphicon glyphicon-home"> Home</a></li>
				<li><a href='/admin/alluser' class="page-scroll glyphicon glyphicon-user"> User</a></li>
				<li><a href="/admin/allcountry" class="page-scroll glyphicon glyphicon-globe"> Countries</a></li>
				<li><a href="/admin/allcity" class="page-scroll glyphicon glyphicon-plane"> Cities</a></li>
				<li><a href="/admin/allloc" class="page-scroll glyphicon glyphicon-screenshot"> Locations</a></li>
				<li><a href="/admin/allhotel" class="page-scroll glyphicon glyphicon-tower"> Hotels</a></li>
				<?php
				if($isLogin){
					?>
					<li><a href="/user/logout" class="page-scroll glyphicon glyphicon-log-out"> LogOut</a></li>
					<?php
				}
				?>
			</ul>
		</div>
		</nav>
	<br><br><br>

<div id="view-content">

	<h3 align="center" > Countries <a href='addcountry'>Add Country</a></h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Country Name</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->count as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td><a class='btn btn-success' href='edit/conid/".$value['id']."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='deletecountry/conid/".$value['id']."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>
	<?php } ?>

</div>
	</div>
		<script src="/bootstrap/js/city_script.js"></script>
		<script src="/bootstrap/js/bootstrap-datepicker.js"></script>
		<script> $('.date_field').datepicker('hide');</script>