
<?php
$isLogin=false;
$user=null;
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (!empty($sessionRead)) {
	$name = $sessionRead->username;
	$isLogin=true;
	$user=$sessionRead;
}
if ($isLogin) {
	$name = $user->username;
}
?>

<h3 align="center" > Control in Your Site  <?= $name ?> </h3>

<a class='btn btn-success' href='alluser'>User</a>
<a class='btn btn-success' href='allcountry'>Countries</a>
<a class='btn btn-danger' href='allcity'>Cities</a>
<a class='btn btn-success' href='allloc'>Locations</a>
<a class='btn btn-success' href='allhotel'>Hotels</a>




